# Generated by Django 3.0.3 on 2020-05-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task Name')),
                ('mode', models.PositiveIntegerField(verbose_name='Mode')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Created'), (1, 'Running'), (2, 'Error/Suspend'), (3, 'Success')], default=0, verbose_name='Status')),
                ('device', models.CharField(max_length=100, verbose_name='Device')),
                ('description', models.CharField(max_length=5000, verbose_name='Description')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Xperf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('port', models.PositiveIntegerField(verbose_name='Port')),
                ('buff', models.PositiveIntegerField(verbose_name='Buff Size')),
                ('parallel', models.PositiveIntegerField(verbose_name='Parallel')),
                ('interval', models.PositiveIntegerField(verbose_name='Interval')),
                ('seconds', models.PositiveIntegerField(verbose_name='Interval')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('Stop_time', models.DateTimeField(auto_now_add=True, verbose_name='Stop Time')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task', to='nix.Task')),
            ],
            options={
                'verbose_name': 'xperf',
                'verbose_name_plural': 'xperfs',
            },
        ),
        migrations.CreateModel(
            name='Perf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(verbose_name='Result')),
                ('time_stamp', models.DateTimeField(auto_now=True, verbose_name='Time Stamp')),
                ('xperf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Xperf', to='nix.Xperf')),
            ],
            options={
                'verbose_name': 'Perf',
                'verbose_name_plural': 'Perfs',
            },
        ),
    ]
