# Generated by Django 3.0.3 on 2020-05-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xperf',
            name='seconds',
            field=models.PositiveIntegerField(verbose_name='seconds'),
        ),
        migrations.AlterField(
            model_name='xperf',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
